<?php

/**
 * @file
 * Handles installation for Commerce USPS module.
 */

/**
 * Implements hook_uninstall().
 */
function commerce_usps_uninstall() {
  $fields = array(
    'commerce_usps_postal_code',
    'commerce_usps_services',
    'commerce_usps_services_int',
    'commerce_usps_connection_address',
    'commerce_usps_user',
    'commerce_usps_show_logo',
    'commerce_usps_log',
  );

  foreach ($fields as $data) {
    //variable_del($data);
  }
}
